language: node_js
node_js:
  - "v11.3.0"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
  - npm install
after_success:
  - npm start
  - firebase deploy --project movie-catalogue-pwa --token $FIREBASE_TOKEN
